### ISSUE TITLE
Error inavlid webpage 

### ISSUE THREAD

**Issue by EllaU** [Flutterwave/flutterwave-react-native#15] opened 2021-01-15 10:08 UTC
Hi Im using PayWithFlutterwave , now when my transaction is either succesful or cancelled i get this error message on the modal 'Webpage not available' error :invalid redirect.My onRedirect prop works just fine but it executes like 30 seconds after the error message.  Ive included redirect_url option to it but it still pops the error. Please help me. I need the error message out completely please! Thanks

**Comment by thecodecafe** [comment] 2021-01-15 12:15
Hi @EllaU, please can you please help with these two things?
1. Can you confirm you're using the most recent version of this library? The library does not use the redirect URL you provide.
2. Can you share your implementation of the PayWithFlutterwave component?
Thanks.

**Comment by EllaU** [comment] 2021-01-16 16:05
"flutterwave-react-native": "^1.0.2", thats the version

 <PayWithFlutterwave
                    style={{marginTop:'5%',borderRadius:10,alignSelf:'center',flexDirection:'row',height:hp('7%'),width:wp('70%')}}
                    onRedirect={handleRedirect}
                    onAbort={()=>navigation.navigate('Register5')}
                    


                    options={{
                      tx_ref: (currentDate+"_"+userid).toString(),//change to unique string,//change to unique string
                      authorization: 'FLWPUBK-2ecd33047f665e8453e97bd8aedf54a0-X',
                      
                      customer: {
                        email: email
                      },
                      
                      amount: parseInt(price),
                      currency:currency,
                      payment_options: 'card,ussd',
                      payment_plan:parseInt(paymentId),
                    }}
                  />

thats the implementation of the component

 const handleRedirect=async(data)=>{
    console.log(data.status)

    if(data.status === 'successful' ){
      fetch('https://wakaati.com/app/success.php',
      {
        method: "POST",
        body: JSON.stringify({  
           amount: price,
           currency: currency,
           userid: userid
    
     })
   }
     ).then(response => response.json())
     .then(data => {
       //welcome
      console.log(data.status)
      });
      
      navigation.navigate('Welcome')
     
    }else{
      console.log(data.status)
      navigation.navigate('Register5') //register5
    }

  }
thats the handleRedirect function

**Comment by thecodecafe** [comment] 2021-01-18 08:13
Hi, @EllaU I've tried using your implementation and it works correctly even with your key, I just saw your update about the delay in execution after redirect.

Here's the thing internally the redirect URL goes to a page that does not exist on our domain, that's why you're seeing the error message on a successful or cancelled transaction, we might look into creating a webpage that does not show that error.

However, the cause of the slow execution of the redirect handler might stem from the way you're managing your component, I can tell the PayWithFlutterwave is in a function component in your code, when not written correctly function components tend to not be "reactive" when you need them to be, please find below two things you can try to do concerning this, if they work or not, please let me know.

1. Define handleRedirect function With useCallback: Always use the callback hook in React to create functions in function components, change `handleRedirect` to the following.
```
const handleRedirect = React.useCallback(async (data) => {
  // handle successful payment
  if (data.status === 'successful') {
    return navigation.navigate('Welcome');
  }
  // navigate to register screen on failure
  navigation.navigate('Register5');
}, [navigation]);
```

2. Convert the component housing the button to a class function.

Please try these options and feedback.

**Comment by EllaU** [comment] 2021-01-19 11:11
Thanks so much for the code ive changed to a class component , I appreciate .
But for now my main issue is still this webpage error showing after succesful or cancelled transaction .Here's a picture 

![error](https://user-images.githubusercontent.com/46875374/105026902-f498fa00-5a03-11eb-9d5e-917dba1d80d0.jpg)

**Comment by thecodecafe** [comment] 2021-01-19 14:08
Hi @EllaU all right, working on a fix for this, are you using Expo?

**Comment by EllaU** [comment] 2021-01-19 15:22
Thanks so much, No I'm not . Im using React Native CLI

**Comment by EllaU** [comment] 2021-01-22 10:37
Hi, sorry ...any update yet?

**Comment by thecodecafe** [comment] 2021-01-22 10:45
Hello @EllaU please try installing from the branch for this fix and let me know if it works.
Use the command below to install.
```
npm i git+https://github.com/Flutterwave/flutterwave-react-native/#fix-redirect-error
```
Let me know how if it fixes it for you.

**Comment by EllaU** [comment] 2021-01-25 09:49
Thanks soooo muchhhh!!, The error page is out . Finally! Thank you.

**Comment by thecodecafe** [comment] 2021-01-25 11:10
Awesome @EllaU, I've made a PR regarding this and will soon be deployed so you can install it directly from npm.
I'll be closing this now issue now.
Thanks!

**Closed by thecodecafe** 2021-01-25 11:10 UTC

**Comment by Ayobamiu** [comment] 2022-02-03 12:29
I am having the same issue

**Comment by amalikmuhd** [comment] 2023-10-06 02:29
@thecodecafe I have whenever I get success or error. I am using expo

**Comment by bytenaija** [comment] 2024-04-22 12:07
I have the same issue. I am using expo SDK 50
