### ISSUE TITLE
Make the payment open on function rather by clicking a predifined button

### ISSUE THREAD

**Issue by bjorndonald** [Flutterwave/flutterwave-react-native#18] opened 2021-03-04 13:14 UTC
Could we try having the payment screen open when we run a function rather than through a predefined button

**Comment by thecodecafe** [comment] 2021-03-15 15:05
Hi, @bjorndonald yes this is possible, can you share your use case so I can better understand what you are trying to achieve? Maybe some code implementation with brevity and also avoid sharing your public keys here.

**Comment by bjorndonald** [comment] 2021-03-16 08:03
This is generally similar to paystack but it will still be a big help
`import {Flutterwave} from 'flutterwave-react-native';

Flutterwave.init({ publicKey: 'pk_key_here' });

Flutterwave.chargeCard({
                    cardNumber: "424242424242",
                    expiryMonth: "09",
                    expiryYear: "21",
                    cvc: "222",
                    tx_ref: "transaction reference can be gotten by initializing a transaction"
                })
`
Only tx_ref will be optional

**Comment by thecodecafe** [comment] 2021-04-28 12:14
Hello @bjorndonald, sorry for catching up on this late, this library only provides access to loading Flutterwave's checkout within your app, we currently don't have a library that allows react-native apps to connect to the API directly. Please I will be closing this issue for now since the issue is out of the library's scope.
Thanks.

**Comment by thecodecafe** [comment] 2021-04-28 12:15
Hello @bjorndonald, sorry for catching up on this late, this library only provides access to loading Flutterwave's checkout within your app, we currently don't have a library that allows react-native apps to connect to the API directly. Please I will be closing this issue for now since the issue is out of the library's scope.
Thanks.

**Closed by thecodecafe** 2021-04-28 12:15 UTC
